### ISSUE TITLE
FrontEnd -  بحث متقدم is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#10]
In  "قوائم الحصر" and  "تظلمات 
بحث متقدم is not working

When clicking on " بحث متقدم" and adding all the data needed then click on "Search", it is not working and doesn't get any response

**Comment by nadagouda** [comment]
@NourhanYoussef This is fixed for searching by address, And it was working perfectly fine for both building number and building name

**Comment by NourhanYoussef** [comment]
It is working for searching for the first time with "Address" or "Building Number" or "Building Name" although the government and region has incorrect values.
But when remove the search text then search with other values, it is not working correctly, Please check it again.

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
