### ISSUE TITLE
Frontend/backend -   تسليم صور المسابقة, إشترك معنا in ندوات و مسابقات is not working and not mapped to any component in the backend

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#12]
تسليم صور المسابقة, إشترك معنا in ندوات و مسابقات is not working and not mapped to any component in the backend

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
إشترك معنا is updated with text 
And "تسليم صور المسابقة" is removed from the frontend.
