### ISSUE TITLE
BackEnd - Competitions, Internal news & Journals,...etc - Almost all the dates field in the backend is not working correctly

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#13]
1.  The "deadline" field is not working correctly, not be able to scroll down and choose the date
2. "Date Published" is not working in "Internal news" category
3. In "Journals", not be able to select dates from the end of the calendar

Please check all the dates mentioned in the backend

**Comment by nadagouda** [comment]
![Screen Shot 2019-04-24 at 2 00 36 AM](https://user-images.githubusercontent.com/46890450/56623540-f4a07600-6634-11e9-9e4c-fe5efdb2c1fe.png)
![Screen Shot 2019-04-24 at 2 00 55 AM](https://user-images.githubusercontent.com/46890450/56623541-f4a07600-6634-11e9-9bd8-f95fcb20d327.png)
![Screen Shot 2019-04-24 at 2 01 45 AM](https://user-images.githubusercontent.com/46890450/56623544-f5390c80-6634-11e9-8a61-05787157455a.png)

Please check the attached screenshots, date fields are working fine.

**Comment by NourhanYoussef** [comment]
@nadagouda Please add the data (large data) then check it.

**Comment by NourhanYoussef** [comment]
@nadagouda Still displaying to me and I can't scroll
![image](https://user-images.githubusercontent.com/49487834/56664897-4da9f180-66a9-11e9-94be-d96b2a2cd8fb.png)

**Comment by nadagouda** [comment]
Checked again, can't reproduce this issue.

**Comment by NourhanYoussef** [comment]
@nadagouda Still failed from myside.

**Comment by NourhanYoussef** [comment]
This is because of the strapi itself, we should scroll from the mouse and is not working from the scroll in the right hand side.
