### ISSUE TITLE
FrontEnd - المزيد in  "أحداث و فعليات" is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#14]
المزيد in  "أحداث و فعليات" is not working

![image](https://user-images.githubusercontent.com/49487834/55975615-ab424500-5c8a-11e9-97bd-f3300704d2c7.png)

**Comment by abdelazizelsaman** [comment]
Please define the expected behavior for "المزيد". 

The current behavior: redirect to "conferences" web page empty with no entries.

Do you mean by "not working" that the "conferences" webpage should contain entries from cms?

**Comment by abdelazizelsaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BackEnd_Conferences is not mapping to FrontEnd. #60](https://trello.com/c/EgJrZkTV/7-backendconferences-is-not-mapping-to-frontend-60)

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
