### ISSUE TITLE
FrontEnd - After Clicking on "المزيد من الأخبار ", the pictures are changed and the uploaded ones is not displayed

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#16]
After Clicking on "المزيد من الأخبار ", the pictures are changed and the uploaded ones is not displayed

Actual Result:
There are one picture which set by default as below
![image](https://user-images.githubusercontent.com/49487834/55976030-87333380-5c8b-11e9-868b-c160b690ea42.png)

Expected Result:
![image](https://user-images.githubusercontent.com/49487834/55976089-a336d500-5c8b-11e9-987c-81b58f8772c7.png)

**Comment by nadagouda** [comment]
@NourhanYoussef  Fixed.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
