### ISSUE TITLE
FrontEnd - The date is not displayed correctly in all the application

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#17]
The date is not displayed correctly in all the application

It is displayed as below 
For example:
![image](https://user-images.githubusercontent.com/49487834/55976173-dda07200-5c8b-11e9-9a92-0dea7730a99e.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
