### ISSUE TITLE
FrontEnd -In الفائزون في المسابقات ,  "المرصد الحضاري" " and "صحافة"- The picture is displayed as black although it was uploaded

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#18]
ندوات و مسابقات1. 
Then
 الفائزون في المسابقات
The picture is displayed as black although it was uploaded as below
![image](https://user-images.githubusercontent.com/49487834/55976414-691a0300-5c8c-11e9-839f-198d89d69456.png)

2. 
المرصد الحضاري
![image](https://user-images.githubusercontent.com/49487834/56093645-87217680-5ecb-11e9-9dac-de6eda1b4437.png)

3. اخر الاخبار
Then
صحافة
![image](https://user-images.githubusercontent.com/49487834/56131292-53a42200-5f87-11e9-967d-07a53c9aa7ea.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
Fixed only from "المرصد الحضاري"
الفائزون في المسابقات and صحافة are failed verification.

**Comment by nadagouda** [comment]
@NourhanYoussef Please try to add new data in the content type and check if it'll be reflected

**Comment by NourhanYoussef** [comment]
@nadagouda I added a new data for "Competition", although it is reflected in the below screenshot
![image](https://user-images.githubusercontent.com/49487834/56693102-e6f5f980-66e3-11e9-86d5-01735728ace8.png)

But it is not reflected in the below
![image](https://user-images.githubusercontent.com/49487834/56693156-09881280-66e4-11e9-9b5f-97764e7076f4.png)

Also, not fixed in "صحافة" although it is link.

**Comment by NourhanYoussef** [comment]
For "الفائزون في المسابقات" is taking the data from "Contestant" and it is working fine
But Still not working for "صحافة"

**Comment by NourhanYoussef** [comment]
Please change it to "No image available"

**Comment by abdelazizelsaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FrontEnd -In الفائزون في المسابقات , "المرصد الحضاري" " and "صحافة"- The picture is displayed as black although it was uploaded #18](https://trello.com/c/0pTRfw1n/17-frontend-in-%D8%A7%D9%84%D9%81%D8%A7%D8%A6%D8%B2%D9%88%D9%86-%D9%81%D9%8A-%D8%A7%D9%84%D9%85%D8%B3%D8%A7%D8%A8%D9%82%D8%A7%D8%AA-%D8%A7%D9%84%D9%85%D8%B1%D8%B5%D8%AF-%D8%A7%D9%84%D8%AD%D8%B6%D8%A7%D8%B1%D9%8A-and-%D8%B5%D8%AD%D8%A7%D9%81%D8%A9-the-picture-is-displayed-as-black-although-it-was-uploaded-18)

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
