### ISSUE TITLE
FrontEnd - مكتبة الجهاز- "YearOfPublisher" field is not displayed in the portal while it is entered in the backend

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#19]
In مكتبة الجهاز , "YearOfPublisher" field is not displayed in the portal while it is entered in the backend as below

![image](https://user-images.githubusercontent.com/49487834/55976525-d168e480-5c8c-11e9-82be-3e5bd016451b.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
