### ISSUE TITLE
FrontEnd - In the above header menu, the links of the sub menu of أهم الخدمات is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#2]
In the above header menu, the links of the sub menu of أهم الخدمات is not working

![image](https://user-images.githubusercontent.com/49487834/55909855-47157780-5bdd-11e9-9026-420a40a012d8.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
