### ISSUE TITLE
FrontEnd/BackEnd - In "مكتبة الجهاز" - "تسجيلات الجهاز" is always empty although there are some data added in the backend

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#24]
In "مكتبة الجهاز" - "تسجيلات الجهاز" is always empty although there are some data added in the backend

![image](https://user-images.githubusercontent.com/49487834/55977146-57395f80-5c8e-11e9-8cac-67e05e0a35ee.png)

![image](https://user-images.githubusercontent.com/49487834/55977172-6f10e380-5c8e-11e9-8eb4-60a8ba4f689b.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This is related to the access of content types in strapi, Fixed.

**Comment by NourhanYoussef** [comment]
@nadagouda Still not be able to display the content.

**Comment by NourhanYoussef** [comment]
Will verify it in the strapi latest version

**Comment by norangamal** [comment]
The issue is still existing and the page is empty.

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
