### ISSUE TITLE
BackEnd - In "Libraries", the author is displayed as "printingNo" in the form of data

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#25]
In "Libraries", the author is displayed as "printingNo" in the form of data

![image](https://user-images.githubusercontent.com/49487834/55977592-7389cc00-5c8f-11e9-9370-b7fe8dc3cef6.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
