### ISSUE TITLE
BackEnd - Governorates Section - When adding "Governorate" then adding "Regions" to this governorate, it is not working correctly

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#26]
When adding "Governorate" then adding "Regions" to this governorate, it is not working correctly

For example: 
1. Add "Aswan"
2. Then add region for Aswan, ex: edfo
3. Select the new one added (Aswan) from "بحث متقدم"  it gives a blank page as below
![image](https://user-images.githubusercontent.com/49487834/55978374-0165b700-5c90-11e9-9f4f-52575312c3e4.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
