### ISSUE TITLE
BackEnd - Some Components have been added in the back-end while it is not reflected with any data or functionality in the portal

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#27]
Some Components have been added in the back-end while it is not reflected with any data or functionality in the portal

1. Albums
2. Conferences
3. Petitions
4. Research
5. Terms and abouts

Maybe some of them is not implemented yet.

**Comment by nadagouda** [comment]
un-used content types have been removed from backend

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
