### ISSUE TITLE
FrontEnd - قوائم الحصر - Search - When searching with a certain value then remove this value, it remains in the same screen after filtering

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#28]
FrontEnd - قوائم الحصر - Search - When searching with a certain value then remove this value, it remains in the same screen after filtering

Steps to reproduce:
1. Open "قوائم الحصر و التظلمات"
2. Then, open "قوائم الحصر"
3. Type any ID and click on "Search"
4. Then remove the value of the search
Actual Result:
It displays the same page, and I should refresh the page to display the original values.
Expected Result:
It should display the page without filtering as the search value is removed
![image](https://user-images.githubusercontent.com/49487834/56093318-50496180-5ec7-11e9-95ec-0454f2253387.png)

And the same issue for "بحث متقدم"

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
