### ISSUE TITLE
FrontEnd - التظلمات - متابعة التظلم - The search is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#29]
FrontEnd - التظلمات - متابعة التظلم - The search is not working

![image](https://user-images.githubusercontent.com/49487834/56093371-46742e00-5ec8-11e9-9f7e-a5750b32d577.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Check the attached screenshot please.

![Screen Shot 2019-04-24 at 10 17 15 AM](https://user-images.githubusercontent.com/46890450/56643592-31429080-667a-11e9-84aa-f79b1e4069d6.png)

**Comment by NourhanYoussef** [comment]
It is working for the first time to search only, Please refer to issue #28
