### ISSUE TITLE
FrontEnd - When click on "مكتبة الجهاز" then click on any other type from the above header menu, it is not working correctly

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#3]
When click on "مكتبة الجهاز" then click on any other type from the header menu:
عن الجهاز
أهم الخدمات
ندوات و مسابقات
مشروعات
الأخبار
It doesn't redirect to the selected type and remains in the same page

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
Fixed for all except this one "أهم الخدمات"=> is not working

**Comment by nadagouda** [comment]
@NourhanYoussef اهم خدمات it scrolls down to its place as it contains more than one service, as it doesn't have a link for an internal page

**Comment by NourhanYoussef** [comment]
Ok, will close it.
