### ISSUE TITLE
FrontEnd/BackEnd - المرصد الحضاري- "ImageURL" field is not displayed in the portal

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#30]
المرصد الحضاري- "ImageURL" field is not displayed in the portal although it was uploaded 

![image](https://user-images.githubusercontent.com/49487834/56093676-ec756780-5ecb-11e9-9f07-199ad699393e.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Replaced the "imageURL" field with "image" which now allows to upload an image, fixed in front-end as well

**Comment by NourhanYoussef** [comment]
@nadagouda Still displayed the same as below
![image](https://user-images.githubusercontent.com/49487834/56662501-69f75f80-66a4-11e9-953b-474b462c87df.png)

**Comment by nadagouda** [comment]
![Screen Shot 2019-04-24 at 5 01 50 PM](https://user-images.githubusercontent.com/46890450/56670236-c497b800-66b2-11e9-9266-735524a83430.png)
@NourhanYoussef Please check again, it's been updated.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
