### ISSUE TITLE
FrontEnd - القوانين و الإستشارات- الأدلة الإرشادية- Is not working correctly

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#31]
الأدلة الإرشادية in القوانين و الإستشارات Is not working correctly although the data was entered in the backend

Frontend:
![image](https://user-images.githubusercontent.com/49487834/56093938-c30a0b00-5ece-11e9-878e-1741a9b043ee.png)

Backend:
![image](https://user-images.githubusercontent.com/49487834/56093949-d9b06200-5ece-11e9-87b5-60f97ea03890.png)

**Comment by nadagouda** [comment]
@NourhanYoussef It displays the data correctly, please check the attached screenshot.
You should add only pdf files.
![Screen Shot 2019-04-24 at 10 19 32 AM](https://user-images.githubusercontent.com/46890450/56643776-926a6400-667a-11e9-9eec-14710ff5eb5c.png)

**Comment by NourhanYoussef** [comment]
It is working fine.
