### ISSUE TITLE
FrontEnd - ندوات و مسابقات - The photo/file is not mapped correctly in the competition

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#32]
The photo/file is not mapped correctly in the competition

![image](https://user-images.githubusercontent.com/49487834/56095439-3a469b80-5edd-11e9-8235-c3948473ae1f.png)

It is displayed as black while the uploaded file should be displayed

**Comment by nadagouda** [comment]
@NourhanYoussef This is working, please check the attached screenshot.

![Screen Shot 2019-04-24 at 5 43 48 PM](https://user-images.githubusercontent.com/46890450/56673463-9b7a2600-66b8-11e9-94db-e8d4c346bf3e.png)

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
