### ISSUE TITLE
FrontEnd -In all the portal for ex: مشروعات and مكتبة الجهاز- If the images are not uploaded, it should be displayed as empty

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#34]
In all the portal for ex: مشروعات and مكتبة الجهاز- If the images are not uploaded, it should be displayed as empty
It should not displayed as below
![image](https://user-images.githubusercontent.com/49487834/56096496-54867680-5ee9-11e9-9516-c80d83584543.png)
![image](https://user-images.githubusercontent.com/49487834/56120247-0d8e9480-5f6e-11e9-8269-6a5614202e97.png)

**Comment by NourhanYoussef** [comment]
Will be changed in all the application to display "No image available"

**Comment by nadagouda** [comment]
Fixed.

**Comment by norangamal** [comment]
Fixed.
<img width="1129" alt="Screen Shot 2019-06-20 at 5 12 38 PM" src="https://user-images.githubusercontent.com/51783494/59860261-aaaae680-937e-11e9-95b8-d1655d8aa509.png">

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
