### ISSUE TITLE
FrontEnd - المزيد  that related to "مشروعات" in the above changing panel is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#35]
المزيد  that related to "مشروعات" in the above changing panel is not working

![image](https://user-images.githubusercontent.com/49487834/56096570-47b65280-5eea-11e9-95c5-1bac02386286.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed.

**Comment by NourhanYoussef** [comment]
@nadagouda Failed Verification, Please check it again.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
