### ISSUE TITLE
FrontEnd - لمجموعة التي ينتمي إليها الكتاب field is displayed in English language in the frontend

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#37]
لمجموعة التي ينتمي إليها الكتاب field is displayed in English language in the Frontend as below

![image](https://user-images.githubusercontent.com/49487834/56133781-949f3500-5f8d-11e9-881f-2925c6927079.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This is fixed.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
