### ISSUE TITLE
FrontEnd - In مكتبة الجهاز - The search is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#38]
In مكتبة الجهاز - The search is not working

![image](https://user-images.githubusercontent.com/49487834/56137199-928ca480-5f94-11e9-8077-a37e6bfe1c35.png)

**Comment by norangamal** [comment]
The Issue is still exists @nadagouda

**Comment by abdelazizelsaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FrontEnd - In مكتبة الجهاز - The search is not working #38](https://trello.com/c/cQjpm5ZO/18-frontend-in-%D9%85%D9%83%D8%AA%D8%A8%D8%A9-%D8%A7%D9%84%D8%AC%D9%87%D8%A7%D8%B2-the-search-is-not-working-38)

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
