### ISSUE TITLE
FrontEnd - HomePage - When click on "ندوة و مسابقات" or "مشروعات", it should display the header of the selected type

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#4]
When click on "ندوة و مسابقات" or "مشروعات", it should display the header of the selected type

1. 
Actual Result: When click on "ندوة و مسابقات, it cuts the header and displays part from "مشروعات" as per the below screenshot
![image](https://user-images.githubusercontent.com/49487834/55910597-19313280-5bdf-11e9-9b7a-449aae3952fe.png)

Expected Result:
![image](https://user-images.githubusercontent.com/49487834/55910661-41209600-5bdf-11e9-902b-c142678e61fd.png)

2. 
Actual Result: When click on مشروعات , it cuts the header and displays part from "أخبار" as per the below screenshot
![image](https://user-images.githubusercontent.com/49487834/55910711-5b5a7400-5bdf-11e9-8969-bdd919744992.png)

Expected Result:
![image](https://user-images.githubusercontent.com/49487834/55910746-6f05da80-5bdf-11e9-985b-f4d14448aefb.png)

**Comment by nadagouda** [comment]
This was changed, as now the navigation menu redirects to the internal page @NourhanYoussef

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification (it s now redirects to its own page instead of the headers of the home page)
