### ISSUE TITLE
Backend - Competitions - The photo logo should be displayed as photo not PDF file

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#40]
In competitions , in the "Photo" field => it should be displayed as photo logo not PDF file

The below logo makes confusion as the expected file should be photo not PDF file
![image](https://user-images.githubusercontent.com/49487834/56198992-472dd100-603c-11e9-8a4b-7a3ed27aa996.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This is built in Strapi itself, we don't develop or enhance it.

**Comment by NourhanYoussef** [comment]
Will check this part.

**Comment by Omar-Handouk** [comment]
Please re-check the issue again in strap

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
