### ISSUE TITLE
Frontend - Home Page - مشروعات - When clicking on "مشروعات", it displays the data for "مشروعات جارية" instead of مشروعات تمت

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#41]
Home Page - مشروعات - When clicking on "مشروعات", it displays incorrect data for "مشروعات تمت"

Steps to reproduce:
1. Open on "Home Page" tab or refresh the page
2. Click on "مشروعات"
3. Check the projects displayed under "مشروعات تمت"
Actual Result: It is the projects which related to "مشروعات جارية" not the one which related to "مشروعات تمت" although it is displayed under "مشروعات تمت"
![image](https://user-images.githubusercontent.com/49487834/56206340-6c2a4000-604c-11e9-995e-038d60a14af6.png)

4. Click on " مشروعات مقترحة or  مشروعات جارية"
5. Then return back to "مشروعات تمت"
Actual Result: It is now displaying the correct projects
![image](https://user-images.githubusercontent.com/49487834/56206454-c0cdbb00-604c-11e9-8254-504871e361c1.png)

Also, After clicking on "المزيد من المشروعات" , it displays the data of "مشروعات جارية" instead of مشروعات تمت until clicking on "    مشروعات مقترحة or  مشروعات تمت then it will display the correct data
Please follow the same above steps after clicking on "المزيد من المشروعات

**Comment by nadagouda** [comment]
Fixed, the correct section is now the one highlighted

**Comment by norangamal** [comment]
There is جارية projects under  مشروعات تمت

<img width="1354" alt="Screen Shot 2019-06-17 at 12 09 40 PM" src="https://user-images.githubusercontent.com/51783494/59597185-8a1e2a80-90f9-11e9-9778-574236ff10e1.png">

**Comment by norangamal** [comment]
I followed the same steps that Nourhan explained above and I get this result after I switched from the مشروعات جارية و مشروعات مقترحة and return back to مشروعات تمت
<img width="1323" alt="Screen Shot 2019-06-17 at 12 22 06 PM" src="https://user-images.githubusercontent.com/51783494/59597723-cef69100-90fa-11e9-9486-dff5a8401fe7.png">

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
