### ISSUE TITLE
Backend - Libraries - When filtering using bookcategory is "history", there are no results displayed although there are some data already exists

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#43]
In Libraries - When filtering using bookcategory is "history", there are no results displayed although there are some data already exists

Actual Result:
![image](https://user-images.githubusercontent.com/49487834/56212097-a2ba8780-6059-11e9-85de-76fa07cc6d46.png)

There are some data already exists for ex:
![image](https://user-images.githubusercontent.com/49487834/56212164-c1208300-6059-11e9-8163-62449c2c864d.png)

![image](https://user-images.githubusercontent.com/49487834/56212212-dd242480-6059-11e9-82a5-71a86acee9fc.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This is out of our scope

**Comment by NourhanYoussef** [comment]
Will verify it in the latest version of strapi.

**Comment by norangamal** [comment]
Fixed now

<img width="1225" alt="Screen Shot 2019-06-20 at 5 26 26 PM" src="https://user-images.githubusercontent.com/51783494/59861168-9bc53380-9380-11e9-8956-a64d948a7068.png">
