### ISSUE TITLE
Frontend - قوائم الحصر - There are a constant sentence always displayed

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#45]
In قوائم الحصر - There are a constant sentence always displayed

![image](https://user-images.githubusercontent.com/49487834/56274013-3e053880-60fe-11e9-995f-cf4e4fed62b8.png)

**Comment by nadagouda** [comment]
@NourhanYoussef Fixed the headline.

**Comment by NourhanYoussef** [comment]
Fixed and Passed Verification.
