### ISSUE TITLE
FrontEnd - التظلمات - متابعة التظلم - "No Rows Found" message is always displayed in the table

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#46]
In التظلمات - متابعة التظلم - "No Rows Found" message is always displayed in the table

![image](https://user-images.githubusercontent.com/49487834/56274419-f59a4a80-60fe-11e9-86c4-fec6e1354eb2.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This is only displayed when there's no data, please check the attached screenshot.

![Screen Shot 2019-04-24 at 10 33 06 AM](https://user-images.githubusercontent.com/46890450/56644663-6a7c0000-667c-11e9-86bf-f718d314b6e0.png)

**Comment by NourhanYoussef** [comment]
@nadagouda But there are data already exist in "SurveyList" in the backend
It is not displayed and When searching using any values, it doesn't display any data.
![image](https://user-images.githubusercontent.com/49487834/56670615-73d48f00-66b3-11e9-8ea2-5a48eeff6849.png)

![image](https://user-images.githubusercontent.com/49487834/56670640-8353d800-66b3-11e9-9cbc-c9f5a9f25c8c.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This section is for data in surveylist that has status value of 'exits'

**Comment by NourhanYoussef** [comment]
@nadagouda I already have 2 with exist value.

**Comment by norangamal** [comment]
Fixed

<img width="1211" alt="Screen Shot 2019-06-20 at 5 35 56 PM" src="https://user-images.githubusercontent.com/51783494/59861917-0034c280-9382-11e9-8255-c388ed2c210b.png">
