### ISSUE TITLE
Frontend - surveylist, Incidents consultingoffice,contestant and projects - When filtering using some fields , it is not working correctly

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#47]
1. In surveylist - When filtering using "RegistrationNumber" (is, is not....etc) , it is not working correctly

![image](https://user-images.githubusercontent.com/49487834/56275872-d2bd6580-6101-11e9-8e28-9bf9458be06f.png)

![image](https://user-images.githubusercontent.com/49487834/56275897-e2d54500-6101-11e9-8f97-9783bb90ac49.png)

2. In "Incident", when filtering using "Subject" (is, is not,....etc) , is not working correctly => Specially if filtering with the first record.

3. In "Condition and Laws", when filtering using "Descrption" (is, is not,....etc), is not working correctly

4. In "Consulting Office", when filtering using "Owner" and "Speciality", is not working correctly

5. a) In "contestant", when filtering using "Phone", is not working correctly => if we searched using phone number, it is not working but if searching using text, it is working.
And b) In "contestant", when filtering using "Status" = applied, is not working correctly 

6.  a) In "Projects", when filtering using "Place"
And b) In "Projects", when filtering using "Details"

**Comment by NourhanYoussef** [comment]
As per Nada, this component is related to strapi itself and is out of our scope.

**Comment by NourhanYoussef** [comment]
Will verify it in the latest version of strapi.

**Comment by norangamal** [comment]
Issue still exists

<img width="982" alt="Screen Shot 2019-06-20 at 5 45 00 PM" src="https://user-images.githubusercontent.com/51783494/59862525-39b9fd80-9383-11e9-80bd-d91c04ae96da.png">


<img width="1170" alt="Screen Shot 2019-06-20 at 5 44 05 PM" src="https://user-images.githubusercontent.com/51783494/59862541-4179a200-9383-11e9-9f6f-346ca64a2d5c.png">

**Comment by abdelazizelsaman** [comment]
There is no error in Strapi side, the actual problem is the filtering process. "RegistrationNumber" is of type "number", which can be filtered using "is greater/lower than or equal" not "is". "is" is used to compare strings only in Strapi.

Here is a screenshot of the process.

![Screenshot at 2019-08-07 15:38:54](https://user-images.githubusercontent.com/38365494/62627378-940a2000-b929-11e9-850a-dac095716e61.png)

**Comment by abdelazizelsaman** [comment]
Needs re-testing
