### ISSUE TITLE
Frontend - قوائم الحصر و التظلمات - Government and Region is not working correctly unless refreshing the page each time.

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#50]
In قوائم الحصر و التظلمات - Government and Region is not working correctly unless refreshing the page each time
Example:
Actual Result:
![image](https://user-images.githubusercontent.com/49487834/56668093-41c12e00-66af-11e9-995e-79cd4fdfd47c.png)

Expected Result:
![image](https://user-images.githubusercontent.com/49487834/56668182-674e3780-66af-11e9-9d20-1f83d70d0e7d.png)

**Comment by nadagouda** [comment]
@NourhanYoussef I can't reproduce the issue, could u please retest

**Comment by NourhanYoussef** [comment]
@nadagouda Can you please try to add some data in the search then click on "search" button then add  another data then search then check the government and region.

**Comment by NourhanYoussef** [comment]
This issue is not reproducible so will close it.
