### ISSUE TITLE
FrontEnd - الأدلة الإرشادية - When there are no data uploaded, it should give an error message

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#51]
When there are no data uploaded, it should give an error message

Actual Result:
![image](https://user-images.githubusercontent.com/49487834/56687399-72688e00-66d6-11e9-9f01-0266ba7552aa.png)

**Comment by nadagouda** [comment]
@NourhanYoussef When there's no data returned from back-end the component itself doesn't get rendered, please check the screenshot.

![Screen Shot 2019-04-24 at 11 11 32 PM](https://user-images.githubusercontent.com/46890450/56694165-671d5e80-66e6-11e9-9bae-436a67662aba.png)

**Comment by NourhanYoussef** [comment]
@nadagouda If one of them is missing or all, the below screenshot is displayed
https://user-images.githubusercontent.com/49487834/56687399-72688e00-66d6-11e9-9f01-0266ba7552aa.png

**Comment by NourhanYoussef** [comment]
Will be revested

**Comment by norangamal** [comment]
When there in no data uploaded the user get this message now:

<img width="1196" alt="Screen Shot 2019-06-18 at 11 00 06 AM" src="https://user-images.githubusercontent.com/51783494/59668220-6241cc00-91b8-11e9-8bc8-83ae01706315.png">

**Comment by abdelazizelsaman** [comment]
Based on my inspection, the reason behind the screenshot above is that the PDF representation method in this tab "الادلة الارشادية" is different from the other tabs. In "الادلة الارشادية", the PDF is rendered in a frame, but in the other tabs, PDF is listed & can be previewed by clicking on a button as shown in the the screenshot below.


![Screenshot at 2019-08-12 17:24:34](https://user-images.githubusercontent.com/38365494/62876871-2ba2b080-bd26-11e9-885d-9c7631158105.png)
**First 2 tabs "القوانين" & "الحدود والإشتراطات"**


![Screenshot at 2019-08-12 17:24:56](https://user-images.githubusercontent.com/38365494/62876875-2c3b4700-bd26-11e9-8cef-d8b3850029f5.png)
**3rd tab with different representation "الادلة الارشادية"**

**Comment by OmarReda** [comment]
adding an empty pdf entry in الادلة الارشادية gives an error.

**Comment by OmarReda** [comment]
Needs to be Closed issue is solved
