### ISSUE TITLE
Frontend - قوائم الحصر و التظلمات - Search Functionality has some issues

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#52]
Search Functionality "بحث متقدم" has some issues:

1. All the fields marked as "Mandatory" with "*" while it is working as any of them I can search for (OR)
2. The search using "Government" and "Region" is not implemented
3. When adding a search text in 
إسم الشارع and
إسم العقارand
رقم العقار
Actual Result: It displayed the data for only one field 
Expected Result: It should display all the data which I search for (If I added some data in Address, Building Name or Building number), it should display 3 records but actually it is displayed only one of them

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
