### ISSUE TITLE
FrontEnd_The numbering of Bullets should be in Arabic if the language is Arabic in pageرؤيتنا وأهدافنا

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#53]
In the Page of رويتنا وآهدافنا the bullets should be in Arabic
<img width="1349" alt="Screen Shot 2019-06-17 at 10 07 28 AM" src="https://user-images.githubusercontent.com/51783494/59589887-25f46a00-90eb-11e9-879b-9ccab5ee4222.png">
 as the context is Arabic

**Comment by Omar-Handouk** [comment]
Fixed @norangamal check the fix please
![Screen Shot 2019-08-04 at 1 29 08 PM](https://user-images.githubusercontent.com/30159338/62423007-eba35400-b6bb-11e9-9348-385f6922da28.png)

**Comment by OmarReda** [comment]
Needs to be closed issue is solved
