### ISSUE TITLE
FrontEnd_at التظلمات page there is missing full stop.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#54]
It should be a full stop in the following highlighted: 

<img width="1338" alt="Screen Shot 2019-06-17 at 10 13 03 AM" src="https://user-images.githubusercontent.com/51783494/59590096-97341d00-90eb-11e9-8ac6-a04c57a2309f.png">

**Comment by Omar-Handouk** [comment]
Fixed @norangamal check the fix please
![Screen Shot 2019-08-04 at 1 56 00 PM](https://user-images.githubusercontent.com/30159338/62423304-a123d680-b6bf-11e9-947d-fcd2c5d92de9.png)
