### ISSUE TITLE
FrontEnd_القوانين والاستشارات page the search arrow should be dimmed if there is no further search result.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#55]
FrontEnd_القوانين والاستشارات page the search arrow should be dimmed if there is no further search result.
There is 2 search results in the مقدمة عن الادلة الارشادية, when the user click on the first search result, the left arrow should be dimmed and the right arrow should be active. (which is not the case as the left arrow is active)
When the user on the second search result the right arrow should be dimmed and the left arrow should be active. (which is not the case as the right arrow is active)

Please,check it.

<img width="1330" alt="Screen Shot 2019-06-17 at 10 59 20 AM" src="https://user-images.githubusercontent.com/51783494/59591899-33abee80-90ef-11e9-86bb-55c865bb255a.png">

<img width="1365" alt="Screen Shot 2019-06-17 at 10 48 49 AM" src="https://user-images.githubusercontent.com/51783494/59591248-fdba3a80-90ed-11e9-90f9-fd98f94caff1.png">

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
