### ISSUE TITLE
FrontEnd_Home page_ after clicking on المزيد on مكاتب استشارية section it lead the user to blank page. 

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#56]
FrontEnd_Home page_ after clicking on المزيد on مكاتب استشارية section it lead the user to blank page and the page is loading only.

<img width="1349" alt="Screen Shot 2019-06-17 at 11 22 35 AM" src="https://user-images.githubusercontent.com/51783494/59593612-8c30bb00-90f2-11e9-9a39-05b30aeb931b.png">

**Comment by Omar-Handouk** [comment]
Fixed the issue, no the page loads properly and displays relevant data from the CMS
![Screenshot at 2019-08-12 22:53:24](https://user-images.githubusercontent.com/30159338/62898416-b3ec7a00-bd55-11e9-99b2-d53273e09814.png)
![Screenshot at 2019-08-12 22:53:54](https://user-images.githubusercontent.com/30159338/62898436-bea70f00-bd55-11e9-9ebd-b5c58a0db8cc.png)
![Screenshot at 2019-08-12 22:54:08](https://user-images.githubusercontent.com/30159338/62898451-c8c90d80-bd55-11e9-97b1-f5de5f055cc0.png)

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
