### ISSUE TITLE
Backend_ Competition-Calendar_accept past date.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#57]

**Comment by norangamal** [comment]
When you create a competition, the Calendar should accept future date only not past date.
Actual: the Calendar accepted past date.

<img width="1172" alt="Screen Shot 2019-06-17 at 2 12 26 PM" src="https://user-images.githubusercontent.com/51783494/59603656-454ebf80-910a-11e9-9fee-5b27a820246d.png">

**Comment by Omar-Handouk** [comment]
Competitions now do not render past competition only current
![Screenshot at 2019-08-12 10:21:00](https://user-images.githubusercontent.com/30159338/62852860-fd53af80-bcea-11e9-805e-0654c6f8827e.png)

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
