### ISSUE TITLE
BackEnd_Conditionsandlaws_Add new Conditionsandlaws tab is not represented fine.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#58]
Add new Conditionsandlaws tab should be represented more clearly than that.

<img width="1329" alt="Screen Shot 2019-06-18 at 10 32 10 AM" src="https://user-images.githubusercontent.com/51783494/59666275-d0848f80-91b4-11e9-8124-e31e0297e46b.png">

**Comment by norangamal** [comment]
And here Also.

<img width="1269" alt="Screen Shot 2019-06-18 at 12 50 38 PM" src="https://user-images.githubusercontent.com/51783494/59676414-d041bf80-91c7-11e9-86bb-2120279685b9.png">

**Comment by norangamal** [comment]
Please check add new button in all the BackEnd.

**Comment by abdelazizelsaman** [comment]
This is a problem with Strapi's UI, modifying the Open-Source project is currently out of scope.

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
