### ISSUE TITLE
BackEnd_Conditionsandlaws_Reset button is not working.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#59]
Reset button is not working in Conditionsandlaws in the BackEnd.
It should reset the data 

<img width="1241" alt="Screen Shot 2019-06-18 at 10 44 45 AM" src="https://user-images.githubusercontent.com/51783494/59667088-6bca3480-91b6-11e9-8f1f-99c8b8454959.png">

**Comment by Omar-Handouk** [comment]
@norangamal You may have misunderstood the purpose of the reset button. The reset button reset the fields to its original form when you currently are editing the field. For example: if you made a new entry the title is empty, if you changed the title **Without Saving the entry** and press the reset field it would reset the field to its original value which is empty.

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
