### ISSUE TITLE
BackEnd_Conferences is not mapping to FrontEnd.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#60]
There is no Conferences in the FrontEnd.

<img width="388" alt="Screen Shot 2019-06-18 at 12 46 58 PM" src="https://user-images.githubusercontent.com/51783494/59676217-590c2b80-91c7-11e9-8023-4a49bdd4eb67.png">

**Comment by abdelazizelsaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BackEnd_Conferences is not mapping to FrontEnd. #60](https://trello.com/c/EgJrZkTV/7-backendconferences-is-not-mapping-to-frontend-60)

**Comment by abdelazizelsaman** [comment]
Conferences is actually implemented in front-end, but has no direct access from the nav bar, it can be accessed by clicking on "المزيد" as shown in the screenshot below. I believe that this is not the intended behavior. Please state the required behavior so we can implement as required.
![Screenshot at 2019-08-15 16:42:30](https://user-images.githubusercontent.com/38365494/63102671-d9f36380-bf7b-11e9-85d6-bc42934e2a45.png)

**Comment by Omar-Handouk** [comment]
Related to issue #14

**Comment by OmarReda** [comment]
Render expired conferences that has past date.
