### ISSUE TITLE
BackEnd_Consultingoffices_ when you add new Consultingoffices, some validations fields require special Character before saving.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#61]
When you add new Consultingoffices in the BackEnd ,the validations fields should require special data like:
PostalCode :this field should require numbering.
PhoneNumbers :this field should accepts numbering only.
Fax: this field should accepts numbering only.
Email: this field should contains @.
Steps to reproduce:
1-Add new Consultingoffices in the BackEnd 
2- Fill the above fields with letters only without adding numbers.
3- Press save.
Actual Results:  Consultingoffices added successfully.  
Expected Results: There should be a validation error that require the user to add the require date which I explained above (numbers / @).

**Comment by Omar-Handouk** [comment]
See issue: #64

Currently the Strapi CMS does not offer input validation for data, this also applies for constraints on addition of fields.

Refer to: https://portal.productboard.com/strapi/1-public-roadmap/c/14-validations
