### ISSUE TITLE
BackEnd_Incidents_Subject and Photographer validation fields should give an error message when the user enter numbers only. 

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#62]
When the user entered numbers only in the Subject  and Photographer validation fields and press Save it saved successfully ,but it shouldn't save, it should  give an error message the user should entered letters only or letters and numbers.

<img width="1212" alt="Screen Shot 2019-06-18 at 2 10 51 PM" src="https://user-images.githubusercontent.com/51783494/59682297-3af9f780-91d6-11e9-8890-781f24eed59a.png">

<img width="1264" alt="Screen Shot 2019-06-18 at 2 35 21 PM" src="https://user-images.githubusercontent.com/51783494/59682374-641a8800-91d6-11e9-829e-73faa11d3311.png">

**Comment by Omar-Handouk** [comment]
See issue: #64 

Currently the Strapi CMS does not offer input validation for data, this also applies for constraints on addition of fields.

Refer to: https://portal.productboard.com/strapi/1-public-roadmap/c/14-validations
