### ISSUE TITLE
BackEnd_Calendar_when you click on the Calendar icon the calendar Can't display.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#63]

**Comment by norangamal** [comment]
In the BackEnd when you click the Calendar icon,the Calendar can't display.
The user should click inside the empty field beside the Calendar icon in order to display the icon.

<img width="632" alt="Screen Shot 2019-06-19 at 11 15 03 AM" src="https://user-images.githubusercontent.com/51783494/59753097-b9f93980-9283-11e9-8573-0d6eb56dad89.png">

**Comment by Omar-Handouk** [comment]
The calendar icon is used to indicate that the field is a date field. The user should click on the input/text box for the calendar for it to show. 
![Screenshot at 2019-08-06 13:44:58](https://user-images.githubusercontent.com/30159338/62537459-b9772b00-b850-11e9-8a36-d6cec7c1db2f.png)

I understand the concern but unfortunately this is something that is implemented in the UI of the CMS and we have no control over it.
