### ISSUE TITLE
BackEnd_Governorate_Filters_The user can press on + sign  Infinite times but there should be a validation here.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#64]
BackEnd_ Governorate _Filters_The user can press on + sign  Infinite times but there should be a validation here.
Steps to reproduce:
1- open Governorate in strapi
2- click on filters.
3- press the (+) sign many times for ex 15 times.
4- The user will still able to add Infinite search by clicking on this + sign.
Expected results: the user should have a validation message when use this +.

<img width="1221" alt="Screen Shot 2019-06-19 at 6 50 52 PM" src="https://user-images.githubusercontent.com/51783494/59784690-5989ec80-92c3-11e9-8d35-21ba81eaed27.png">

<img width="1228" alt="Screen Shot 2019-06-19 at 6 27 38 PM" src="https://user-images.githubusercontent.com/51783494/59784338-7a9e0d80-92c2-11e9-86ee-db5b8739ed97.png">

**Comment by Omar-Handouk** [comment]
Currently the Strapi CMS does not offer input validation for data, this also applies for constraints on addition of fields. 

Refer to: https://portal.productboard.com/strapi/1-public-roadmap/c/14-validations
