### ISSUE TITLE
BackEnd_Governorate_when the user click on Add New Governorate and leave the Governorate name field empty then press save it is saved successfully but the save button shouldn't save empty data. 

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#65]

**Comment by norangamal** [comment]
![Uploading Screen Shot 2019-06-19 at 6.59.18 PM.png…]()


![Uploading Screen Shot 2019-06-19 at 6.59.18 PM.png…]()

**Comment by norangamal** [comment]
<img width="1240" alt="Screen Shot 2019-06-19 at 6 53 43 PM" src="https://user-images.githubusercontent.com/51783494/59796074-ff962080-92dc-11e9-8628-de914662334a.png">

<img width="1239" alt="Screen Shot 2019-06-19 at 6 59 18 PM" src="https://user-images.githubusercontent.com/51783494/59796125-1f2d4900-92dd-11e9-9fcb-b9022f476123.png">

**Comment by Omar-Handouk** [comment]
Added a constraint on the gov. field such that the field must contain a value.
Unique constraint should be added such that we can not create a gov. with duplicate name

**Comment by Omar-Handouk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [z\\](https://trello.com/c/gNGQvJvs/25-z)

**Comment by OmarReda** [comment]
Needs to be closed issue is solved
