### ISSUE TITLE
FrontEnd_المكتبة العامة_ When the user write any word and press on بحث the user didn't find any search result.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#66]
FrontEnd_المكتبة العامة_ When the user write any word and press on بحث the user didn't find any search result.
Steps to reproduce:
1- Open the مكتبة الجهاز.
2-Select المكتبة العامة
3- write any search word like"حضارة"
4- press on بحث
5- The search result page didn't change ,it should contains the search results that contains word حضارة.
<img width="1160" alt="Screen Shot 2019-06-20 at 2 21 57 PM" src="https://user-images.githubusercontent.com/51783494/59849267-67914900-9367-11e9-9f3c-1d5ce8986c50.png">

**Comment by norangamal** [comment]
Also,when the user select one option from the filter of البحث في then click on بحث the search results is not related to the filter.

<img width="1242" alt="Screen Shot 2019-06-20 at 2 35 40 PM" src="https://user-images.githubusercontent.com/51783494/59849934-44679900-9369-11e9-958e-727cc284fdea.png">

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
