### ISSUE TITLE
FrontEnd_قوائم الحصر _ The page number is mix between Arabic and English.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#67]
In the قوائم الحصر in the end of the page,the number of the page is mix between Arabic and English,it should be Arabic only or English only, according to the language the user use.

<img width="1202" alt="Screen Shot 2019-06-20 at 4 58 24 PM" src="https://user-images.githubusercontent.com/51783494/59859554-39b6ff00-937d-11e9-90f1-04692573a1e7.png">

**Comment by Omar-Handouk** [comment]
Potential fixing method: https://github.com/tannerlinsley/react-table/issues/196

**Comment by Omar-Handouk** [comment]
Fixed English words to Arabic. Unfortunately the numerals can not be changed as the react module used does not allow the changing of the numerals @norangamal please check the fix 
![Screen Shot 2019-08-04 at 12 22 02 PM](https://user-images.githubusercontent.com/30159338/62422441-0c1ae080-b6b3-11e9-9426-ec799761305d.png)

**Comment by OmarReda** [comment]
Needs to be closed issue is solved
