### ISSUE TITLE
FrontEnd_مكتبة الجهاز_ in المكتبة العامة_ the user found that there is No Image Available under the uploaded image

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#68]
FrontEnd_مكتبة الجهاز_ in المكتبة العامة_ the user found that there is No Image Available under the uploaded image.
 No Image Available shouldn't be displayed.

<img width="1108" alt="Screen Shot 2019-06-20 at 5 18 46 PM" src="https://user-images.githubusercontent.com/51783494/59860658-a3380d00-937f-11e9-961e-30140c08a77b.png">

**Comment by OmarReda** [comment]
https://www.youtube.com/embed/hrEXfvjSLN8

**Comment by OmarReda** [comment]
Needs to be closed issue is solved
