### ISSUE TITLE
BackEnd_مكتبة الجهاز_in تسجيلات الجهاز_ is empty although it should be filled with data.

### ISSUE THREAD

**Issue by norangamal** [ansgohar/urbanharmony#69]
BackEnd_مكتبة الجهاز_in تسجيلات الجهاز_ is empty although it should be filled with data.

Steps to reproduce:
1- I uploaded the a video in the BackEnd from videos.
2- I  opened the FrontEnd and check تسجيلات الجهاز
3- I found it empty.

<img width="1212" alt="Screen Shot 2019-06-20 at 5 53 27 PM" src="https://user-images.githubusercontent.com/51783494/59863476-12643000-9385-11e9-90ab-ea628a435349.png">

**Comment by abdelazizelsaman** [comment]
This is a duplicate issue, for more on this follow issue #24

**Comment by OmarReda** [comment]
Needs to be closed issue is solved.
