### ISSUE TITLE
FrontEnd - Home Page - All the links in the footer of the home page is not working

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#7]
All the links in the footer of the home page is not working

![image](https://user-images.githubusercontent.com/49487834/55911382-d7a18700-5be0-11e9-8384-d243122c3eaa.png)

**Comment by nadagouda** [comment]
@NourhanYoussef This is fixed for اتصل بنا and مواقع ذات صلة and for the others we don't have the links to be added

**Comment by NourhanYoussef** [comment]
Fixed for  اتصل بنا and مواقع ذات صلة
But We need to add the link for the rest of them.

**Comment by nadagouda** [comment]
@NourhanYoussef That should be provided from urbanHarmony side

**Comment by norangamal** [comment]
من نحن ،الخصوصية، الشروط والاحكام is not working

**Comment by norangamal** [comment]
At the footer من نحن
النون في نحو   is not fine

<img width="1345" alt="Screen Shot 2019-06-17 at 10 03 24 AM" src="https://user-images.githubusercontent.com/51783494/59589544-7f0fce00-90ea-11e9-822d-027f19a68949.png">

**Comment by abdelazizelsaman** [comment]
The problem causing the absence ن at the end of نحن is the font family. To prove so, we tried adding ن or any letter with 2 possible shapes (example: ت، خ ، ف unlike ة) at the end of each word in the footer ending with the same problem happening to نحن.

Fix:
Add space break after each word ending in a letter with 2 possible shapes, to ensure that the word has ended.

**Comment by Omar-Handouk** [comment]
Fixed @norangamal check the fix please
![Screen Shot 2019-08-04 at 12 22 21 PM](https://user-images.githubusercontent.com/30159338/62422532-5e103600-b6b4-11e9-9d8d-0767fad68fed.png)

**Comment by OmarReda** [comment]
Needs to be Closed issue solved.
