### ISSUE TITLE
FronEnd - Home Page - When drilling down to any link from the home page and click one of the above header menu options it is not working 

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#8]
When drilling down to any link from the home page ex. "رؤيتنا و اهدافنا", "قوانين",...etc and then click one of the above header menu options except home page, it is not working and doesn't get any response

**Comment by nadagouda** [comment]
@NourhanYoussef This is fixed.

**Comment by NourhanYoussef** [comment]
@nadagouda Fixed for all except "أهم الخدمات"

**Comment by NourhanYoussef** [comment]
Will close it as per Nada's comment is issue #3
