### ISSUE TITLE
Frontend_المشروعات_in_مشروعات تمت_Wrong active tab in the <li> inside the <ul>

### ISSUE THREAD

**Issue by OmarReda** [ansgohar/urbanharmony#86]
The active tag on opening the page should be مشروعات جارية instead of مشروعات تمت 
In order to be right with the data represented below.\

NOTE: This is a issue that was mentioned before and can simply be solved in the frontend perspective.

#Enhancement

**Comment by Omar-Handouk** [comment]
Fixed in pull request
