### ISSUE TITLE
FrontEnd - The view of "قوائم الحصر"w "تظلمات" needs to be enhanced specially the footer of the table 

### ISSUE THREAD

**Issue by NourhanYoussef** [ansgohar/urbanharmony#9]
The view of "قوائم الحصر"w "تظلمات" needs to be enhanced specially the footer of the table as it is displayed in English language although all the pages in Arabic

![image](https://user-images.githubusercontent.com/49487834/55911789-a8d7e080-5be1-11e9-8fba-f80cce7b060c.png)

**Comment by Omar-Handouk** [comment]
See issue #67

**Comment by OmarReda** [comment]
Needs to be closed the issue is solved.
